# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 2汽车之家极速版

on:
  workflow_dispatch:
  schedule:
     - cron: '29 0-15 * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        QCZJ_GetUserInfoURL: ${{ secrets.QCZJ_GetUserInfoURL2 }}
        QCZJ_GetUserInfoHEADER: ${{ secrets.QCZJ_GetUserInfoHEADER2 }}
        QCZJ_coinBODY: ${{ secrets.QCZJ_coinBODY2 }}
        QCZJ_taskBODY: ${{ secrets.QCZJ_taskBODY2 }}		
        QCZJ_activityBODY: ${{ secrets.QCZJ_activityBODY2 }}	
        QCZJ_GoldcoinBODY: ${{ secrets.QCZJ_GoldcoinBODY2 }}	
        QCZJ_videoBODY: ${{ secrets.QCZJ_videoBODY2 }}	        
        QCZJ_WelfarevideoBODY: ${{ secrets.QCZJ_WelfarevideoBODY2 }}	
        QCZJ_WelfareBODY: ${{ secrets.QCZJ_WelfareBODY2 }}	
        QCZJ_addCoinBODY: ${{ secrets.QCZJ_addCoinBODY2 }}
        QCZJ_addCoin2BODY: ${{ secrets.QCZJ_addCoin2BODY2 }}
        QCZJ_reportAssHEADER: ${{ secrets.QCZJ_reportAssHEADER2 }}
        QCZJ_reportAssBODY: ${{ secrets.QCZJ_reportAssBODY2 }}
        QCZJ_cointowalletBODY: ${{ secrets.QCZJ_cointowalletBODY2 }}
         
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/ziye12/QCZJSPEED.git ~/QCZJSPEED
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        if: env.QCZJ_GetUserInfoURL
        run: |
          cd ~/QCZJSPEED
          npm install
      - name: '运行 【2汽车之家极速版】'
        if: env.QCZJ_GetUserInfoURL
        run: |
          cd ~/QCZJSPEED
          node Task/qczjspeed.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}

    
