# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 2汽车之家极速版

on:
  workflow_dispatch:
  schedule:
     - cron: '29 0-15 * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        QCZJ_GetUserInfoURL: ${{ secrets.2QCZJ_GetUserInfoURL }}
        QCZJ_GetUserInfoHEADER: ${{ secrets.2QCZJ_GetUserInfoHEADER }}
        QCZJ_coinBODY: ${{ secrets.2QCZJ_coinBODY }}
        QCZJ_taskBODY: ${{ secrets.2QCZJ_taskBODY }}		
        QCZJ_activityBODY: ${{ secrets.2QCZJ_activityBODY }}	
        QCZJ_GoldcoinBODY: ${{ secrets.2QCZJ_GoldcoinBODY }}	
        QCZJ_videoBODY: ${{ secrets.2QCZJ_videoBODY }}	        
        QCZJ_WelfarevideoBODY: ${{ secrets.2QCZJ_WelfarevideoBODY }}	
        QCZJ_WelfareBODY: ${{ secrets.2QCZJ_WelfareBODY }}	
        QCZJ_addCoinBODY: ${{ secrets.2QCZJ_addCoinBODY }}
        QCZJ_addCoin2BODY: ${{ secrets.2QCZJ_addCoin2BODY }}
        QCZJ_reportAssHEADER: ${{ secrets.2QCZJ_reportAssHEADER }}
        QCZJ_reportAssBODY: ${{ secrets.2QCZJ_reportAssBODY }}
        QCZJ_cointowalletBODY: ${{ secrets.2QCZJ_cointowalletBODY }}
         
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/ziye12/QCZJSPEED.git ~/QCZJSPEED
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        if: env.QCZJ_GetUserInfoURL
        run: |
          cd ~/QCZJSPEED
          npm install
      - name: '运行 【2汽车之家极速版】'
        if: env.QCZJ_GetUserInfoURL
        run: |
          cd ~/QCZJSPEED
          node Task/qczjspeed.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}

    
